# This playbook updates an ubuntu server or desktop installation
# using apt.
# Version 20.04+

---
- hosts: ubuntu
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all apt packages
      apt:
        upgrade: dist

    - name: Remove unused dependencies
      apt:
        autoremove: true

    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required
      reboot:
      when: reboot_required_file.stat.exists == true
